# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2J1MPEUd-SJbRc3MPXPRfam_mj1M2zP
"""

import numpy as np
import pandas

df = pandas.read_csv('insurance-data.csv')
df

# What is the percentage of female smokers?
per = df[(df['sex'] == 'female') & (df['smoker'] == 'yes')].shape[0] / df[df['sex'] == 'female'].shape[0] * 100
print("{:.2f} %".format(per))

# get the maximum charge row
maxx = df['charges'].max()
df[df['charges'] == maxx]['region']

# Which gender has the maximum insurance rate?
df[df['charges'] == maxx]['sex']

## 1.5. what is the average percentage of female smoker age?
df[(df['sex'] == 'female') & (df['smoker'] == 'yes')]['age'].mean()

## 1.6. What is the percentage of males who hase children insurance?
per  = (df[(df['sex'] == 'male') & (df['children'] > 0 )].shape[0] )/(df[(df['sex'] == 'male')].shape[0])*100
print("{:.2f} %".format(per))

## 1.7. What are the percentage of the females who hase children insurance?
per  = (df[(df['sex'] == 'female') & (df['children'] > 0 )].shape[0] )/(df[(df['sex'] == 'female')].shape[0])*100
print("{:.2f} %".format(per))

## 1.8. what are the maximum number of children associated with male parent assurance?
df[df['sex'] == 'male']['children'].max()

# 1.9. What are the maximum number of children associated with female parent assurance?
df[df['sex'] == 'female']['children'].max()

## 1.10. Which city has the maximum female insurance total charge ?
df[(df['sex'] == 'female') & (df['charges'] == maxx)]['region']

